### PR TITLE
t/ckeditor5-editor-decoupled/10: Updated the build to the latest DecoupledEditor API 

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Updated the build to the latest `DecoupledEditor` class API (see ckeditor/ckeditor5-editor-decoupled#10).

---

Requires https://github.com/ckeditor/ckeditor5-editor-decoupled/pull/11.

### CODE REVIEW

**Comment by oleq** [comment]
The build process is broken 

```

ERROR in ../ckeditor5-easy-image/src/cloudservicesuploadadapter.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor-cloud-services-core/src/uploadgateway/uploadgateway' in '/Users/oleq/CK/5/ckeditor5/packages/ckeditor5-easy-image/src'
 @ ../ckeditor5-easy-image/src/cloudservicesuploadadapter.js 12:0-99
 @ ../ckeditor5-easy-image/src/easyimage.js
 @ ./src/ckeditor.js

ERROR in ../ckeditor5-easy-image/src/cloudservicesuploadadapter.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-cloud-services/src/cloudservices' in '/Users/oleq/CK/5/ckeditor5/packages/ckeditor5-easy-image/src'
 @ ../ckeditor5-easy-image/src/cloudservicesuploadadapter.js 13:0-81
 @ ../ckeditor5-easy-image/src/easyimage.js
 @ ./src/ckeditor.js
```

**Comment by Reinmar** [comment]
Do you have this locally? We renamed `@ckeditor/ckeditor-cloud-services-core` recently. Did you update to that?

**Comment by Reinmar** [comment]
Works like a charm for me.

**Comment by Reinmar** [comment]
OK, there's another problem. Only using the latest master of ckeditor5-dev you'll be able to compile a build now. That's due to:

```
commit 6c69057249c8db63f0342fce7643b8707d3dc634
Merge: 9924e65 d80d161
Author: Piotrek Koszuliński <pkoszulinski@gmail.com>
Date:   Tue Mar 27 17:15:42 2018 +0200

    Merge pull request #385 from ckeditor/t/ckeditor5/914

    Fix: Enabled builds to work with RequireJS. Closes ckeditor/ckeditor5#914.

    BREAKING CHANGES: Due to a new format of translation snippets the new version of `CKEditor5WebpackPlugin` will only be compatible with CKEditor 5 v1.0.0-beta.2 or later.
```

I'm not able to release this for now because it will break fresh installations (in case someone will do `npm i --save-dev @ckeditor/ckeditor5-dev-webpack-plugin`).

**Comment by Reinmar** [comment]
I'm adding `BREAKING CHANGE` section in the commit message because the API of the build is based on the API of the editor and it's good to broadcast such crucial information.

**Pull request merged**
